

name: ADSB FRONTEND
on:
push:
  branches:
    - master


jobs:
build:
  
   runs-on: ubuntu-latest


   strategy:
     matrix:
        node-version: ["22.x"]


   steps:
     - name: Install SSH Keys    
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
         known_hosts: "placeholder-for-known-hosts"


     - name: Add Known Hosts
       run: ssh-keyscan -H ${{ secrets.SERVER_DEPLOY_HOST }} >> ~/.ssh/known_hosts


     - name: Checkout UPNMG Codes
       uses: actions/checkout@v2
     - name: Installing Node JS ${{ matrix.node-version }}   
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
         cache: yarn


     - run: yarn install


     - run: yarn run format


     - name: Building the service for deployment
       run: yarn run build


     - name: Deploying APP To Master
       run: rsync -a -r -d package.json processes.json  ./dist ${{ secrets.SERVER_DEPLOY_USER }}@${{ secrets.SERVER_DEPLOY_HOST }}:${{secrets.SERVER_DEPLOY_PATH}}




